### PR TITLE
Fix issues with flaky bulk actions/update specs

### LINKED ISSUE #2693: Fix the flakey tagging spec
We have intermittent failures when the full test suite is run. My guess is due to an ordering issue and data hanging around.

### PR DESCRIPTION
**Pull request by mejackreed**
Paired w/ @jkeck on this one.

Fixes #2693 

Have rerun CI `3` times with all 🍏

### CODE REVIEW

File: spec/controllers/spotlight/bulk_actions_controller_spec.rb [hunk 1]
```diff
@@ -2,12 +2,18 @@
...
 describe Spotlight::BulkActionsController, type: :controller do
   routes { Spotlight::Engine.routes }
-  let(:exhibit) { FactoryBot.create(:exhibit) }
+  let(:exhibit) { FactoryBot.create(:skinny_exhibit) }
 
-  before do
-    allow(Spotlight::ChangeVisibilityJob).to receive(:perform_later)
+  # rubocop:disable RSpec/BeforeAfterAll
+  before(:all) do
+    ActiveJob::Base.queue_adapter = :test
```
Comment (cbeer) [inline spec/controllers/spotlight/bulk_actions_controller_spec.rb:9]: fwiw, i couldn't find any reason we're using `:inline` at all: https://github.com/projectblacklight/spotlight/pull/2698

Comment (mejackreed) [reply spec/controllers/spotlight/bulk_actions_controller_spec.rb:9]: Got it thanks.. I'll cherry pick that in and then remove the before/after blocks.

Comment (mejackreed) [reply spec/controllers/spotlight/bulk_actions_controller_spec.rb:9]: Scratch that.. I still have to set `ActiveJob::Base.queue_adapter = :test` as the ` Internal::Application.config.active_job.queue_adapter` change doesn't seem to have the same impact.
