### PR TITLE
Fix CSV Upload job to set FeaturedImage url instead of direct mounted…

### LINKED ISSUE #1743: CSV Upload not working
v0.33.3 af2ac698ac3e30075c1c493dd9c1af99e579df10

Upload item works as expected. Upload multiple items does not. 

I get the message confirming the csv has been uploaded.

screen shot 2017-02-10 at 8 10 53 am 2

The logs have no exceptions:

```
I, [2017-02-10T14:10:37.524357 #30048]  INFO -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8] Started GET "/spotlight/test/resources/new" for 10.0.2.2 at 2017-02-10 14:10:37 +0000
I, [2017-02-10T14:10:37.525506 #30048]  INFO -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8] Processing by Spotlight::ResourcesController#new as HTML
I, [2017-02-10T14:10:37.525581 #30048]  INFO -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]   Parameters: {"exhibit_id"=>"test"}
D, [2017-02-10T14:10:37.527295 #30048] DEBUG -- :   User Load (3.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
I, [2017-02-10T14:10:37.528115 #30048]  INFO -- : [ActiveJob] [Spotlight::AddUploadsFromCSV] [f7185c21-3db2-4ff6-91ea-6775f6aa5288] Performing Spotlight::AddUploadsFromCSV from Async(default) with arguments: [{"url"=>"https://oaktrust.library.tamu.edu/bitstream/handle/1969.1/129094/CML_WWI_0157a.jpf.jpg", "full_title_tesim"=>"Ypres picture 123", "spotlight_upload_description_tesim"=>"This is a test of the CSV upload", "spotlight_upload_attribution_tesim"=>nil, "spotlight_upload_date_tesim"=>nil, "curator-notes_tesim"=>"Special Curator Notes", "mwb_notes_tesim"=>"Special Collection Notes"}], #<GlobalID:0x007f511afb0870 @uri=#<URI::GID gid://spotlight/Spotlight::Exhibit/1>>, #<GlobalID:0x007f511afabb18 @uri=#<URI::GID gid://spotlight/User/2>>
I, [2017-02-10T14:10:37.528731 #30048]  INFO -- : [ActiveJob] [Spotlight::AddUploadsFromCSV] [f7185c21-3db2-4ff6-91ea-6775f6aa5288] Performed Spotlight::AddUploadsFromCSV from Async(default) in 0.53ms
D, [2017-02-10T14:10:37.530066 #30048] DEBUG -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2017-02-10T14:10:37.539185 #30048] DEBUG -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]   Spotlight::Exhibit Load (0.6ms)  SELECT  "spotlight_exhibits".* FROM "spotlight_exhibits" WHERE "spotlight_exhibits"."slug" = $1 LIMIT $2  [["slug", "test"], ["LIMIT", 1]]
D, [2017-02-10T14:10:37.541866 #30048] DEBUG -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]   Spotlight::Site Load (0.6ms)  SELECT  "spotlight_sites".* FROM "spotlight_sites" ORDER BY "spotlight_sites"."id" ASC LIMIT $1  [["LIMIT", 1]]
D, [2017-02-10T14:10:37.543393 #30048] DEBUG -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]    (0.5ms)  SELECT COUNT(*) FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = $1 AND "spotlight_roles"."role" = $2 AND "spotlight_roles"."resource_type" = 'Spotlight::Site' AND "spotlight_roles"."resource_id" = 1  [["user_id", 2], ["role", "admin"]]
D, [2017-02-10T14:10:37.544473 #30048] DEBUG -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]    (0.5ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = $1 AND "spotlight_roles"."resource_type" = $2 AND "spotlight_roles"."role" = $3  [["user_id", 2], ["resource_type", "Spotlight::Exhibit"], ["role", "admin"]]
D, [2017-02-10T14:10:37.545066 #30048] DEBUG -- : [36ea34e8-f3e7-478a-a31b-e3c36214e1a8]   CACHE (0.0ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = $1 AND "spotlight_roles"."resource_type" = $2 AND "spotlight_roles"."role" = $3  [["user_id", 2], ["resource_type", "Spotlight::Exhibit"], ["role", "admin"]]
```

Solr does not receive any new entries. And the images are not stored in the public/uploads/spotlight/featured_image directory.

### PR DESCRIPTION
**Pull request by jkeck**
… upload.

Closes #1743

### CODE REVIEW

File: spec/jobs/spotlight/add_uploads_from_csv_spec.rb [hunk 1]
```diff
@@ -26,11 +26,12 @@
...
 
   it 'creates uploaded resources for each row of data' do
-    expect(Spotlight::Resources::Upload).to receive(:new).with(hash_including(remote_url_url: 'x')).and_return(resource_x)
-    expect(Spotlight::Resources::Upload).to receive(:new).with(hash_including(remote_url_url: 'y')).and_return(resource_y)
+    upload = FactoryGirl.create(:uploaded_resource)
+    expect(Spotlight::Resources::Upload).to receive(:new).at_least(:once).and_return(upload)
 
-    expect(resource_x).to receive(:save_and_index)
-    expect(resource_y).to receive(:save_and_index)
+    expect(upload).to receive(:build_upload).with(remote_image_url: 'x').and_call_original
```
Comment (jkeck) [inline spec/jobs/spotlight/add_uploads_from_csv_spec.rb]: Hoping `.and_call_original` will keep this from passing in the future if associations change underneath.
